Fix #253 Cannot read property 'then' of null in Transport.js issue.
opensearch-project/opensearch-js pull request #254
Opened 2022-06-14 05:36 UTC by alexrayan

### Description

Porting a fix for "Cannot read property 'then' of null in Transport.js issue".
based on the original fix for the same issue in elastic/elasticsearch-js client lib here: https://github.com/elastic/elasticsearch-js/pull/1594

### Issues Resolved

Fix #253

### Check List

- [x] All tests pass

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-06-17 19:37 UTC, ananzh commented
Hi @alexrayan, trying to reproduce and verify the fix here, but got some issues. Here is [the detail ](https://github.com/opensearch-project/opensearch-js/issues/253#issuecomment-1159175349).

2022-06-20 18:03 UTC, ananzh reviewed
nice, just one minor issue

2022-06-20 19:35 UTC, alexrayan commented on test/unit/client.test.js
> +test('Issue #1521 with callbacks', t => {
@ananzh Updated! Thank you :) 
Sorry for the delay with the response. I am able to see the test failing on `"Issue #253 with callbacks"` in my local without the code change and the test passing with the code fix. 
We actually encountered this issue in our own production flow which is using callbacks when we switched to ES version 7 from ES version 5.

2022-06-21 17:13 UTC, ananzh approved these changes
nice~

2022-07-05 09:02 UTC, rawpixel-vincent commented
this fix our issue where the opensearch client is throwing errors on every requests

2022-07-05 22:12 UTC, alexrayan commented
@ananzh Are these any plans to merge this PR to the code base? Looks like it requires more than 1 approval

2022-07-05 22:34 UTC, kavilla requested changes
Hello @alexrayan,

Thanks for doing this! The changes look good but one thing to note is that it would appear the code is copied from the fork after the licensing change.

For the source code there isn't much you can but the tests has references to Elasticsearch. Could we clean up these tests to avoid any issues with licensing.

Thank you again!

2022-07-06 02:55 UTC, alexrayan commented
> Hello @alexrayan,
> 
> Thanks for doing this! The changes look good but one thing to note is that it would appear the code is copied from the fork after the licensing change.
> 
> For the source code there isn't much you can but the tests has references to Elasticsearch. Could we clean up these tests to avoid any issues with licensing.
> 
> Thank you again!

Hi @kavilla! Sure, let me cleanup the tests and remove the refs shortly.

2022-08-26 19:15 UTC, dblock commented
@alexrayan Want to finish this?

2022-08-26 21:55 UTC, rawpixel-vincent commented
@alexrayan thanks for this 🙏🏻  

cleaned up the unit tests

https://github.com/alexrayan/opensearch-js/pull/3


<img width="1075" alt="Screen Shot 2022-08-27 at 04 52 29" src="https://user-images.githubusercontent.com/22284209/186995835-06304bb6-d968-400b-a439-2662db811bb4.png">

2022-08-26 22:06 UTC, rawpixel-vincent commented
if that helps I rebased the commits to remove any ref to the elasticsearch codebase in #283

2022-08-28 06:53 UTC, alexrayan commented
@rawpixel-vincent Thank you for that! Appreciate it. Apologies for the delay. Life and work got in the way so wasn't able to find time to clean up the tests to remove the ES references.

2022-09-06 06:58 UTC, alexrayan commented
Implemented with the following PR https://github.com/opensearch-project/opensearch-js/pull/283/files, so closing mine.

2022-09-06 06:58 UTC, closed without merging