Fix typo cause it will always trigger JSON11 parse
opensearch-project/opensearch-js pull request #889
Opened 2024-10-29 15:48 UTC by Hailong-am

### Description

Fix typo cause it will always trigger JSON11 parse.

if the json string has number in it, `numeralsAreNumbers` will always be true. 

`(val < Number.MAX_SAFE_INTEGER || val > Number.MAX_SAFE_INTEGER) ` 

should changed to `(val < Number.MIN_SAFE_INTEGER || val > Number.MAX_SAFE_INTEGER) `

https://github.com/opensearch-project/opensearch-js/blob/92884503d80269ba08099040ce20c6aac9a2c4ab/lib/Serializer.js#L101-L107

then it will always trigger JSON11 parse

https://github.com/opensearch-project/opensearch-js/blob/92884503d80269ba08099040ce20c6aac9a2c4ab/lib/Serializer.js#L128-L137

### Issues Resolved

_List any issues this PR will resolve, e.g. Closes [...]._

### Check List

- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] Linter check was successfull - `yarn run lint` doesn't show any errors
- [ ] Commits are signed per the DCO using --signoff
- [ ] Changelog was updated.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-29 19:26 UTC, dblock requested changes
Thanks, could you please add a test?

2024-10-29 23:31 UTC, AMoo-Miki commented
> Thanks, could you please add a test?

Since we have positive tests, we should add negative tests.

2024-10-30 02:55 UTC, Hailong-am commented
> > Thanks, could you please add a test?
> 
> Since we have positive tests, we should add negative tests.

Thanks, a negative tests added. @dblock @AMoo-Miki

2024-10-30 09:11 UTC, dblock approved these changes

2024-10-30 09:12 UTC, merged

2024-11-08 22:55 UTC, AMoo-Miki commented
OSD needs this in 2.x. It would be great if we had a release for it too.

2024-11-12 16:04 UTC, nhtruong commented
I'll cut a release today

2024-11-12 22:47 UTC, nhtruong commented
@AMoo-Miki https://www.npmjs.com/package/@opensearch-project/opensearch/v/2.13.0